# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Flutter App for Windows and macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # 確保給 GITHUB_TOKEN 寫入權限

jobs:
  # build-windows:
  #   name: Build for Windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     # Set up Flutter on Windows
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.22.2'
  #         channel: 'stable'

  #     - name: Install Dependencies
  #       run: flutter pub get

  #     # Run Flutter build for Windows
  #     - name: Build Windows app
  #       run: flutter build windows

  #     # 打包成zip檔
  #     - name: Package Windows Build
  #       run: zip -r my_app_windows.zip build/windows/x64/runner/Release/

  #     # 上傳打包檔案到 Release
  #     - name: Upload Release Asset
  #       uses: actions/upload-release-asset@v1
  #       with:
  #         upload_url: ${{ github.event.release.upload_url }}
  #         asset_path: ./my_app_windows.zip
  #         asset_name: my_app_windows.zip
  #         asset_content_type: application/zip

  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.22.2'

      - name: Install project dependencies
        run: flutter pub get
      # - name: Generate intermediates
      #   run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop

      - name: Build artifacts
        run: flutter build windows --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          # filename: flutter1-${{github.ref_name}}-windows.zip
          filename: flutter1-windows.zip
          directory: build/windows/x64/runner/Release

      - name: List Files
        run: dir

      - name: List Build Files
        run: dir build/windows/x64/runner/Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Releases
          path: flutter1-windows.zip
          
      # - name: Extract version from pubspec.yaml
      #   id: extract_version
      #   run: |
      #     version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
      #     echo "VERSION=$version" >> $GITHUB_ENV
      
      - name: Extract version from pubspec.yaml (Windows)
        id: extract_version
        run: |
          $version = (Get-Content pubspec.yaml | Select-String '^version: ' | ForEach-Object { $_.Line.Split(' ')[1].Trim() })
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "Version: $version"
      - name: Fetch Git Tags
        run: git fetch --tags
        shell: pwsh

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if (-not (git tag -l "v$env:VERSION")) {
            echo "TAG_EXISTS=false" >> $env:GITHUB_ENV
          } else {
            echo "TAG_EXISTS=true" >> $env:GITHUB_ENV
          }
        shell: pwsh

      - name: Create Git Tag
        if: env.TAG_EXISTS == 'false'
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v$env:VERSION"
          git push origin "v$env:VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify Tag
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          $new_version = "$env:VERSION-build-$env:GITHUB_RUN_NUMBER"
          echo "VERSION=$new_version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/x64/runner/Release/flutter1-windows.zip"
          tag: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # build-macos:
  #   name: Build for macOS
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     # Set up Flutter on macOS
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.22.2'
  #         channel: 'stable'

  #     - name: Install Dependencies
  #       run: flutter pub get

  #     # Run Flutter build for macOS
  #     - name: Build macOS app
  #       run: flutter build macos

  #     # Optionally, you can upload the build artifacts
  #     - name: Upload macOS Build
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: macos-build
  #         path: build/macos/Build/Products/Release/

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: dart test
